dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - cd tests; pytest core_tests.py
  - cd tests; pytest util_tests.py
  - cd tests; pytest io_tests.py