dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - pytest tests/core_tests.py
  - pytest tests/util_tests.py
  - pytest tests/io_tests.py